export const ROLES = ["Owner", "User"];

export const CONTACTS = [
  {
    id: "0",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "1",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "2",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
  {
    id: "3",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "4",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "5",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
  {
    id: "6",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "7",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "8",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
  {
    id: "9",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "10",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "11",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
  {
    id: "12",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "13",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "14",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
  {
    id: "15",
    firstName: "Oliver",
    lastName: "Smith",
    emails: ["oliver@example.com", "smith@google.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "16",
    firstName: "James",
    lastName: "Bond",
    emails: ["bond@work.com"],
    role: "Owner",
    createdAt: "September 24,2022",
  },
  {
    id: "17",
    firstName: "Steven",
    lastName: "Strange",
    emails: ["steven@marvel.com"],
    role: "User",
    createdAt: "September 24,2022",
  },
];

export const TAGS = [
  "Getting Started",
  "Onboarding",
  "User Flow",
  "UX",
  "Bugs",
  "V2",
];

export const NOTES = [
  {
    id: "0",
    title: "How to claim the warranty?",
    description:
      "This is something I found in the Figma design file. So please don't mind",
    assignedContact: "Oliver Smith",
    tags: ["Getting Started"],
    lastUpdated: "September 24,2022",
    isModified: false,
  },
  {
    id: "1",
    title: "Write a blog",
    description:
      "This is something I found in the Figma design file. So please don't mind",
    assignedContact: "James Bond",
    tags: ["Getting Started"],
    lastUpdated: "September 24,2022",
    isModified: false,
  },
  {
    id: "2",
    title: "Enjoy your time",
    description:
      "This is something I found in the Figma design file. So please don't mind",
    assignedContact: "Oliver Smith",
    tags: ["Getting Started"],
    lastUpdated: "September 24,2022",
    isModified: false,
  },
];
